apm install atom-beautify
apm install autocomplete-elixir
apm install autocomplete-go
apm install builder-go
apm install dash
apm install docblockr
apm install file-icons
apm install go-config
apm install go-debug
apm install go-get
apm install go-plus
apm install godoc
apm install gofmt
apm install gometalinter-linter
apm install gorename
apm install jsonpp
apm install language-docker
apm install language-dots
apm install language-elixir
apm install language-go
apm install language-ignore
apm install language-protobuf
apm install language-rust
apm install linter
apm install linter-docker
apm install linter-elixirc
apm install linter-eslint
apm install linter-protocol-buffer
apm install linter-rust
apm install markdown-preview-plus
apm install mathjax-wrapper
apm install minimap
apm install minimap-git-diff
apm install native-ui
apm install navigator-go
apm install set-syntax
apm install sort-lines
apm install tester-go